services:
  dev:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.dev) || (test ! -e .entrypoint.dev && yarn install && yarn start)"
    ports:
    - 3000:3000

  e2e:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.e2e) || (test ! -e .entrypoint.e2e && yarn install && yarn cypress)"
    environment:
    - DISPLAY=novnc:0.0
    - BASE_URL=http://dev.opinion-ate-react.com.br:3000
    depends_on:
    - novnc
    links:
    - "dev:dev.opinion-ate-react.com.br"

  novnc:
    image: theasp/novnc:latest
    ports:
    - 48080:8080
    environment:
    - DISPLAY_WIDTH=1600
    - DISPLAY_HEIGHT=968
    - RUN_XTERM=no
