services:
  build:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.build) || (test ! -e .entrypoint.build && yarn install && yarn build)"
    environment:
    - DISABLE_ESLINT_PLUGIN=true

  lint:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.lint) || (test ! -e .entrypoint.lint && yarn install && yarn lint)"

  unit:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.unit) || (test ! -e .entrypoint.unit && yarn install && yarn test --watchAll)"

  dev:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.dev) || (test ! -e .entrypoint.dev && yarn install && yarn start)"
    ports:
    - 3000:3000
    environment:
    - DISABLE_ESLINT_PLUGIN=true

  e2e:
    image: cypress/included:14.3.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source .entrypoint.e2e) || (test ! -e .entrypoint.e2e && yarn install && yarn cypress)"
    environment:
    - DISPLAY=novnc:0.0
    - BASE_URL=http://dev.opinion-ate-react.com.br:3000
    depends_on:
    - novnc
    links:
    - "dev:dev.opinion-ate-react.com.br"

  novnc:
    image: theasp/novnc:latest
    ports:
    - 48080:8080
    environment:
    - DISPLAY_WIDTH=1600
    - DISPLAY_HEIGHT=968
    - RUN_XTERM=no
    volumes:
    - .:/ws
    entrypoint: bash -xc "source /ws/.entrypoint.novnc || (test ! -e /ws/.entrypoint.novnc && /app/entrypoint.sh)"
