services:
  build:
    image: cypress/included:14.3.2
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source /ws/.entrypoint.build) || (test ! -e /ws/.entrypoint.build && yarn install && yarn build)"
    environment:
    - DISABLE_ESLINT_PLUGIN=true

  lint:
    image: cypress/included:14.3.2
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source /ws/.entrypoint.lint) || (test ! -e /ws/.entrypoint.lint && yarn install && yarn lint)"

  unit:
    image: cypress/included:14.3.2
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source /ws/.entrypoint.unit) || (test ! -e /ws/.entrypoint.unit && yarn install && yarn test --watchAll)"

  dev:
    image: cypress/included:14.3.2
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source /ws/.entrypoint.dev) || (test ! -e /ws/.entrypoint.dev && yarn install && yarn start --open=false)"
    ports:
    - 3000:3000
    environment:
    - DISABLE_ESLINT_PLUGIN=true

  e2e-open:
    image: cypress/included:14.3.2
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source /ws/.entrypoint.e2e-open) || (test ! -e /ws/.entrypoint.e2e-open && yarn install && yarn e2e:open)"
    environment:
    - DISPLAY=novnc:0.0
    - BASE_URL=http://dev.opinion-ate-react.com.br:3000
    depends_on:
    - novnc
    - dev
    links:
    - "dev:dev.opinion-ate-react.com.br"

  e2e-run:
    image: cypress/included:14.3.2
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -xc "(source /ws/.entrypoint.e2e-run) || (test ! -e /ws/.entrypoint.e2e-run && yarn install && yarn e2e:run)"
    environment:
    - BASE_URL=http://dev.opinion-ate-react.com.br:3000
    depends_on:
    - dev
    links:
    - "dev:dev.opinion-ate-react.com.br"

  novnc:
    image: theasp/novnc:latest
    ports:
    - 48080:8080
    environment:
    - DISPLAY_WIDTH=1600
    - DISPLAY_HEIGHT=968
    - RUN_XTERM=no
    volumes:
    - .:/ws
    entrypoint: bash -xc "source /ws/.entrypoint.novnc || (test ! -e /ws/.entrypoint.novnc && /app/entrypoint.sh)"
