name: test
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./opinion-ate
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: lint
      run: yarn lint
    - name: unit tests
      run: yarn test --watchAll=false
    - name: e2e tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        start: yarn start
        wait-on: 'http://localhost:3000'
        working-directory: ./opinion-ate
